language: java
install: true
script: mvn clean package -DskipTests=true
jdk:
- openjdk15
services:
- postgresql
before_install:
- psql -c 'CREATE DATABASE forum' -U postgres
env:
  global:
  - CODECOV_TOKEN="13cd1a37-e9c1-4285-afcb-8913f1d970c9"
sudo: false
after_success:
- bash <(curl -s https://codecov.io/bash)
notifications:
  email:
    recipients:
    - dda.90@mail.ru
    on_success: never
    on_failure: always
deploy:
  provider: heroku
  api_key:
    secure: Ih6J8vrmhdByuxvzRmhExUbGB9AKAyIA3nJy91FrIqrCD2F+0Aqquhj2uDq71agRSN8Kcv+nJkAebyImXJdZUMNbuH73lb8S+OEVC2C9RZseB8wpaQvyGFCgnJjgy7y43L7F4ZGqPDt7mK1kMr7590Y/qsKALMJqBtsrGuKdeCmqwI2Vg8At/3dCA73wU6BnC9kBU1v0H1MQgAJQnqgksJ9oVMz8iR8t4jw9t2qWrgdzwc/IDOCb/dWgW7aUTP/CQmOYyczpgE//uuHnAF/isLi/c7Ez5vKuUtgiqDRExprt3XSzQwXvGVR+X6q1sHxfIRNbtF5fRbfPrcAlZYemrQvDr2osJa7g4epVNEAnHj0IT6ghu9pa9JgmNRbpSNWvOU/d25VoBs+gI/xqLaMqgUBMNN3Kfqm+WGhRhEKgSwQ9u7ick3QgrydnFgH4rqioBYWhymC5RmMIrDXOvo0Lnrulos3HTVitUdf8ONaXB1ODzCgckEcsderzjMLCQ7KV+nW+y5uiOiNr/xg776HYiXRbhmy4VBFPlFIeh1hxRzp3x/hAyvxFvkHZU1IR5iZ6LBZbsIOT0U4DOtKG8hlAYUhwoE95C2uGMb8U1nthdBL5OnyOGsHn9TA1UFg2Me6F+u+0E3y1pu/NSD/omb0FC93c/KGCgcKvI4cZ16nawKI=
  app: immense-waters-90323